import javafx.stage.*;
import javafx.scene.*;
import javafx.geometry.*;
import javafx.scene.effect.*;
import javafx.scene.paint.*;
import javafx.scene.input.*;
import javafx.scene.layout.*;
import javafx.scene.text.*;
import javafx.scene.control.*;
import javafx.application.*;
import javafx.scene.image.*;
import javafx.scene.canvas.*;
import javafx.scene.shape.*;
import javafx.scene.transform.*;
import java.util.*;

public class colors extends Application{
    public static void main(String[] args){
        launch(args);
    }
    public void start(Stage stage1){
        Group f = new Group();
        Circle ck = new Circle(600,450,40);
        Rotate ro = new Rotate();
        ro.setAngle(90);
        ro.setPivotX(4);
        ro.setPivotY(4);
        ck.setFill(Color.RED);
        Rectangle rr = new Rectangle(400,100,60,300);
        Text t = new Text();
        Text t2 = new Text("WORLD ON A WIRE");
        t.setFill(Color.RED);
        t.setText("DAN THE MAN");
        t.setX(500);
        t.setY(300);
        t.setFont(Font.font(null,FontWeight.BOLD,40));
        t2.setFill(Color.YELLOW);
        t2.setFont(Font.font(null,FontWeight.BOLD,30));
        t2.setX(500);
        t2.setY(400);
        DropShadow ds = new DropShadow();
        ds.setColor(Color.GREY);
        ds.setOffsetX(2);
        ds.setOffsetY(2);
        ds.setSpread(3);
        ds.setHeight(5);
        ds.setWidth(5);
        ds.setRadius(4);
        ds.setBlurType(BlurType.GAUSSIAN);
        t.setEffect(ds);
        InnerShadow is = new InnerShadow();
        is.setColor(Color.PURPLE);
        is.setOffsetX(2);
        is.setOffsetY(2);
        is.setHeight(5);
        is.setWidth(5);
        is.setRadius(4);
        is.setBlurType(BlurType.GAUSSIAN);        
        t2.setEffect(is);
        Scene s1 = new Scene(f,720,480);
        Circle c1 = new Circle();
        Circle c2 = new Circle();
        Shadow sh = new Shadow();
        Lighting lll = new Lighting();
        rr.setFill(Color.BLUE);
        sh.setWidth(2);
        sh.setHeight(2);
        sh.setRadius(2);
        sh.setColor(Color.VIOLET);
        sh.setBlurType(BlurType.GAUSSIAN);
        rr.setEffect(sh);
        ImageInput im = new ImageInput();
        im.setSource(new Image("zinc.jpg"));
        Blend b = new Blend();
        c1.setCenterX(240);
        c1.setCenterY(120);
        c1.setRadius(40);
        c1.setFill(Color.YELLOW);
        c2.setCenterX(20);
        c2.setCenterY(50);
        c2.setRadius(50);
        c2.setEffect(im);
        Reflection r = new Reflection();
        r.setTopOpacity(0.6);
        r.setBottomOpacity(0.0);
        r.setTopOffset(0.0);
        r.setFraction(0.7);
        GaussianBlur gb = new GaussianBlur();
        List<String> l = getParameters().getRaw();
        gb.setRadius(Integer.parseInt(l.get(0)));
        ImageView im1 = new ImageView(new Image("lost.jpg"));
        ImageView im2 = new ImageView(new Image("mac.jpg"));
        ImageView im3 = new ImageView(new Image("blue1.png"));
        Light.Distant ld = new Light.Distant();
        Light.Spot ld2 = new Light.Spot();
        Light.Point ld4 = new Light.Point();
        ld.setAzimuth(45);
        ld.setElevation(90);
        ld2.setX(450);
        ld2.setY(100);
        ld2.setZ(50);
        ld4.setX(400);
        ld4.setY(320);
        ld4.setZ(20);
        ld4.setColor(Color.GREY);
        Lighting ld1 = new Lighting(ld);
        Lighting ld3 = new Lighting(ld2);
        Lighting ld5 = new Lighting();
        ld5.setLight(ld4);
        SepiaTone sp = new SepiaTone();
        sp.setLevel(0.8);
        im1.setEffect(gb);
        im1.setEffect(r);
        im2.setEffect(sp);
        ck.setEffect(ld5);
        t.setEffect(ds);
        ColorInput ci = new ColorInput(220,115,30,60,Color.RED);
        b.setTopInput(ci);
        b.setMode(BlendMode.DIFFERENCE);
        c1.setEffect(b);
        im1.setEffect(lll);
        rr.getTransforms().addAll(ro);
        f.getChildren().addAll(im1,rr,t,t2,ck);
        stage1.setScene(s1);
        stage1.show();
    }
}